name: Bug Report
description: Report an issue with supported versions of Bliss
body:
  - type: markdown
    attributes:
      value: |
        Please do not use GitHub issues to post ideas.
        Ideas should be discussed on the [Violet Moon discord](https://discord.gg/SFrYxxD).
  - type: input
    id: mod-version
    attributes:
      label: Bliss version
      placeholder: eg. 1.0.2
    validations:
      required: true
  - type: input
    attributes:
      label: "The latest.log file"
      description: "Please use a paste site such as [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc."
  - type: textarea
    attributes:
      label: Issue description
      placeholder: A description of the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. First step
        2. Second step
        3. etc...
  - type: textarea
    attributes:
      label: Other information
      description: Any other relevant information that is related to this issue, such as other mods and their versions.
